format: '%(asctime)s  [%(levelname)s]  %(name)s - %(message)s'
datefmt: '%Y-%m-%d %H:%M:%S'
console:
  level: DEBUG
files:
  'main.log':
    level: INFO
    maxsize: 1M
    count: 3
  'error.log':
    level: ERROR
    maxsize: 1M
    count: 3
